[theme]
# A cor dos destaques (Sliders, Checkboxes, Botões)
primaryColor = "#2323FF" 

# Opcional: Se quiser forçar o fundo do site a ser claro ou escuro
base = "dark" 

# Cor de fundo principal
backgroundColor = "#000000"

# Cor da barra lateral (Sidebar)
secondaryBackgroundColor = "#514d4d"

# Cor do texto
textColor = "#FFFAFA"